### ISSUE TITLE
BERT pre-training with large batch size

### ISSUE THREAD

**Issue by cavdard** [NVIDIA/DeepLearningExamples#101]
Hi,
For pre-training, it is suggested to use batch size of 14 on V100 32G GPU. Is it possible to fit a larger batch size(max sequence length 512). e.g. 32 on V100 32 GB with fp16 and xla?

**Comment by swethmandava** [comment]
It runs out of memory for Batch Size = 16 for me.

**Comment by cavdard** [comment]
Thank you.

**Comment by 652994331** [comment]
@swethmandava @cavdard  Hi, can i ask a quick question, if we are using the code with report_loss = FALSE. and 8 gpus. what batch size are we actually using? train_batch_size you input or train_batch_size * 8 ?
if it's latter, could you please show me where the scale calculation is in the code?
(I only found it in if report_loss = true, that's why i ask if we use report_loss = False what gonna happen then). Thanks  (I asked this in the issue part)

**Comment by swethmandava** [comment]
Covered in #368
