### ISSUE TITLE
Error in training for Tensorflow-SSD

### ISSUE THREAD

**Issue by pista10** [NVIDIA/DeepLearningExamples#102]
I  got errors in training SSD which DataLossError or Key grad_shift_counter not found in checkpoint.

 ./examples/SSD320_FP32_1GPU.sh : -> 
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
         [[{{node IteratorGetNext}}]]
         [[{{node IteratorGetNext}}]]

./examples/SSD320_FP16_1GPU.sh : ->
tensorflow.python.framework.errors_impl.NotFoundError: Key grad_shift_counter not found in checkpoint
         [[node save/RestoreV2_1 (defined at /workdir/models/research/object_detection/model_lib.py:490) ]]

What is the problem?
I wonder a lot of WARNINGS, 
WARNING:root:Variable [resnet_v1_50/fpn/bottom_up_block5/BatchNorm/beta] is not available in checkpoint
WARNING:root:Variable [resnet_v1_50/fpn/bottom_up_block5/BatchNorm/gamma] is not available in checkpoint
WARNING:root:Variable [resnet_v1_50/fpn/bottom_up_block5/BatchNorm/moving_mean] is not available in checkpoint
WARNING:root:Variable [resnet_v1_50/fpn/bottom_up_block5/BatchNorm/moving_variance] is not available in checkpoint .....
 Thank you.

**Comment by nluehr** [comment]
This error usually indicates that you are attempting to start training with AMP enabled from a checkpoint saved in a non-AMP run.

AMP saves its loss scaling parameters (current loss scaler and iterations since last observed NaN) in the checkpoint.

**Comment by pista10** [comment]
Thank you for your response.

Is the checkpoint file from http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz in download_all.sh not suitable for AMP training?
Where can i get the correct checkpoint file?

And why does the error occur with SSD320_FP32_1GPU.sh (non-AMP training)?

**Comment by mwawrzos** [comment]
The ResNet checkpoint is valid both for AMP and FP32 training.

I have reproduced your issue with `DataLossError`. I have sent a merge request #112 that fixes your problem. **Thanks for reporting the issue!** With my fix you have to rerun the [dataset preparation step from the Quick Start Guide](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Detection/SSD#3-download-and-preprocess-the-dataset). If you have done this step before, you can run following bash commands to avoid re-downloading the dataset archives:
```
cd <data_dir_path> # go to the directory where `download_all.sh` stored the dataset before
mkdir raw-data     # create the dir fitting the updated download script
mv *.zip raw-data  # move dataset archives to the right place
cd -               # go back to the prewious working directory
```
Now you can run `download_all.sh` script, as described in the [Quick Start Guide](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Detection/SSD#3-download-and-preprocess-the-dataset), (please, use absolute paths for<data_dir_path> and <checkpoint_dir_path>).

I was not able to reproduce the second issue:
>  ./examples/SSD320_FP16_1GPU.sh : ->
tensorflow.python.framework.errors_impl.NotFoundError: Key grad_shift_counter not found in checkpoint
[[node save/RestoreV2_1 (defined at /workdir/models/research/object_detection/model_lib.py:490) ]]

I was following the [Quick Start Guide](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Detection/SSD#quick-start-guide) and your error have not shown either on the latest commit (81b1b024e155884431d968ddf1dace7e85ada9b2) nor on previous TF/SSD example change (0663b67c1afe9979c9767ed63c7e719b1d0629b9). I was running training with the command:
```
bash ./examples/SSD320_FP16_8GPU.sh /checkpoints
```

Can you try to run training again with changes from #112? It would be great to hear, that the problem is solved. However, if you are still facing the problem, can you put some more details about your case?
* Could you share the exact command you are using to run training?
* Are you using the container build following the instructions from the [Quick Start Guide](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Detection/SSD#quick-start-guide)?
* Can you share a full training log or just wider context around the error from the logs?
