### ISSUE TITLE
How to view the predictions from VNET? 

### ISSUE THREAD

**Issue by cndu234** [NVIDIA/DeepLearningExamples#1030]
I trained vnet on hippocampus data as given in the quick start guide
I run the command `vnet-predict.py` as given in the guide and obtained a file with exstn `.pkl` in temp/predictions folder 
How do I actually view the predictions?

**Comment by mmarcinkiewicz** [comment]
Hello @sindhura234 !
The `.pkl` file is a python pickle - you can open it using the `pickle` module, as explained in, for example, [python wiki](https://wiki.python.org/moin/UsingPickle).

Since the data is 3D there's no easy way to view it easily. A good starting point would be to use `matplotlib` to plot each slice of the prediction.
