### ISSUE TITLE
 DeepLearningExamples/DGLPyTorch/DrugDiscovery/SE3Transformer/ Feature requested -- installation guide for linux without Docker

### ISSUE THREAD

**Issue by rainwala** [NVIDIA/DeepLearningExamples#1038]
Hello, Thank you very much for this great work you've done optimising the SE3Transformer. Would it be possible to provide instructions for how to install all of the dependencies to get the "train.sh" script working on a linux (i.e. Ubuntu 18) machine without using Docker? I want to play with the code and do some model surgery, taking some layers and making a different type of model for a differnet training task, and I think that will be less cumbersome to do outside of a Docker container rather than within one.

**Comment by pribalta** [comment]
Hi @rainwala, we distribute our models inside NVIDIA containers because they simplify the setup and ensure you are getting the same results we're getting. Their usage is extensively documented: https://docs.nvidia.com/deeplearning/frameworks/user-guide/index.html

PyThon IDE's can run code inside docker containers (e.g., PyCharm) including debugging. If you want to reproduce the setup in our Docker container locally please refer to our documentation :)
