### ISSUE TITLE
TSPP - OSError: libcusparse.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by quetdn** [NVIDIA/DeepLearningExamples#1269]
TSPP - Container generated from pytorch:23.01-py3, fails when training the electricity modelset. 

**Describe the bug**
python launch_training.py model=tft dataset=electricity trainer/criterion=quantile
Traceback (most recent call last):
  File "launch_training.py", line 23, in <module>
    from training.utils import set_seed, get_optimization_objectives
  File "/workspace/training/utils.py", line 15, in <module>
    import dgl
  File "/usr/local/lib/python3.8/dist-packages/dgl/__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "/usr/local/lib/python3.8/dist-packages/dgl/backend/__init__.py", line 95, in <module>
    load_backend(get_preferred_backend())
  File "/usr/local/lib/python3.8/dist-packages/dgl/backend/__init__.py", line 41, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "/usr/local/lib/python3.8/dist-packages/dgl/_ffi/base.py", line 44, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/usr/local/lib/python3.8/dist-packages/dgl/_ffi/base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: libcusparse.so.11: cannot open shared object file: No such file or directory**

**To Reproduce**
change image FROM in Dockerfile
-  ARG FROM_IMAGE_NAME=nvcr.io/nvidia/pytorch:**23.01**-py3 
Build image:
- docker build -t tspp-2301 .
Run container:
- docker run -it --gpus all --ipc=host --network=host -v /mydatasets/:/workspace/datasets/ tspp-2301 bash
Run training: 
python launch_training.py model=tft dataset=electricity trainer/criterion=quantile

**Expected behavior**
It works fine when launched in a tspp container generated from pytorch:22.12-py3

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): 
- * tspp from pytorch:23.01-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB):
- * GPU 0: NVIDIA GeForce RTX 3060
- * GPU 1: NVIDIA GeForce RTX 3060
* CUDA driver version (e.g. 418.67):
- * NVIDIA-SMI 525.78.01    Driver Version: 525.78.01    CUDA Version: 12.0

**Comment by IzzyPutterman** [comment]
Thanks for the report!  The 23.01 PyTorch container is the first to use a CUDA 12 version.  To my knowledge pip/conda do not yet have a DGL version which supports CUDA 12.  The DGL page shows the latest as CUDA 11.7: https://www.dgl.ai/pages/start.html

Is there any specific reason why you would like to use the 23.01 PyTorch container, or would 22.12 and earlier work?  

We were able to come up with a solution for this issue that involves building DGL from source if using 23.01 is necessary.  First, since the DGL API has changed since the version we released with, one needs to change the line [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/data/datasets.py#L41) to be `dgl.transforms` instead of `dgl.transform`.  
Next comment out [line 49 in the Dockerfile](https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/Dockerfile#L49) and the [dgl-cu111 in requirements.txt](https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/requirements.txt#L25) and build.


Then once running the container execute these steps
```
cd /tmp/
git clone --recurse-submodules https://github.com/dmlc/dgl.git

apt-get update

apt-get install -y build-essential python3-dev make cmake

cd dgl/ && mkdir build && cd build

export NCCL_ROOT=/usr

cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release  -DUSE_CUDA=ON -DCUDA_ARCH_BIN="60 70 80 90" -DCUDA_ARCH_PTX="90" -DCUDA_ARCH_NAME="Manual"  -DBUILD_TORCH=ON  -DUSE_NCCL=ON   -DUSE_SYSTEM_NCCL=ON -DBUILD_WITH_SHARED_NCCL=ON  -DUSE_AVX=ON  -DBUILD_SPARSE=ON  && cmake --build .

cd ../python  && python setup.py bdist_wheel  && pip install ./dist/dgl*.whl
```

Let us know if you face any issues with the steps here or further issues with the repo.

**Comment by quetdn** [comment]
Hi Izzy, 
I don't have a particular need to use the 23.01 image. I realized that it was released and tried it. But, since you gave me these instructions, I have tested them and they have worked perfectly. They solved the issue.
So I'll keep using 22.12 -which works fine so far- until all compatibilities are met.
Thanks for your help.

**Comment by IzzyPutterman** [comment]
That makes sense and thanks again for the report!
