### ISSUE TITLE
[NCF/TF] Evaluation time calculation

### ISSUE THREAD

**Issue by mankeyboy** [NVIDIA/DeepLearningExamples#374]
Related to **NCF/Tensorflow(s)** 
*(e.g. GNMT/PyTorch or FasterTransformer/All)*

**Evaluation time calculation for final throughput calculation**
In [this](https://github.com/NVIDIA/DeepLearningExamples/blob/784eb0d8ca144ce2cee448ee88d8718c84b5fb5d/TensorFlow/Recommendation/NCF/ncf.py#L401) line in the NCF Recommender using Tensorflow codebase, the eval time is put after all the mpi reduce operations have completed. Looking closer, however, all that this portion is doing is calculating the values of overall evaluation metrics rather than a given inference task (in this case, recommending from a batch).  
Should it not make more sense to have eval time calculation happen before the mpi reduce step since it isn't directly related with inference but instead with the metrics that come after inference?

**To Reproduce**
1. Use the nvidia-docker image for tensorflow and build from the steps in the README.
2. Set "..."
2. Launch '...'

**Expected behavior**

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3):
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB):
* CUDA driver version (e.g. 418.67):

**Comment by tgrel** [comment]
You're right, the current solution includes the MPI reduce calls into eval time, which is used to calculate throughput. This is not perfect. However, this is a very small reduction (just 4 floating point numbers total). I've just benchmarked it and the time to communicate them is about 3ms on a DGX1V when using 4 GPUs. Therefore, you can treat the inference throughput measurement in the training script as a little pessimistic. The exact throughput numbers would be a bit higher.

However, I understand you might want the exact value. That's why we're maintaing a [dedicated script called inference.py](https://github.com/NVIDIA/DeepLearningExamples/blob/784eb0d8ca144ce2cee448ee88d8718c84b5fb5d/TensorFlow/Recommendation/NCF/inference.py). You can use it to accurately measure inference performance (both throughput and latency).

I'm closing this issue since the inference.py already provides the functionality requested. Please reopen if you have any further questions.

**Comment by mankeyboy** [comment]
Thanks for the clarification, I'll have a look at inference.py.
