### ISSUE TITLE
How to adjust the hyper parameters when using V100 32G

### ISSUE THREAD

**Issue by liuyanfeng543** [NVIDIA/DeepLearningExamples#38]
When I used 8*V100 32G to train tansformer, I found that the results of V100 32G  were not significantly different with V100 16G if I didn't adjust hyper parameters, or even decreased. I increased the batch size, but the effect was not obvious. How should I adjust it to fully reflect the advantages of 32G V100?

**Comment by jbaczek** [comment]
Hi, V100 32G is a very similar chip to V100 16G. The difference is only in memory amount thus the computation is performed at roughly the same speed. The Transformer model performance is bound by amount of computation not by a memory, so you wont get any advantage of using V100 32G. Also if you use bigger batch size your convergence rate can decrease due to theoretic reasons.
