### ISSUE TITLE
How to enable XLA:CPU

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/DeepLearningExamples#445]
Related to **Model/Framework(s)** 
DeepLearningExamples/TensorFlow/Classification/RN50v1.5

**Describe the bug**
`2020-04-03 16:43:24.704161: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1648] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.et that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the ene.`

**Expected behavior**
Having XLA:CPU  enabled

**Environment**
* Container versio: nvcr.io/nvidia/tensorflow:20.02-tf1-py3
* GPUs in the system: 8x Tesla V100-SXM2-16GB
* CUDA driver version: 440.33.01

**Comment by pribalta** [comment]
@vilmara do you require having XLA enabled in CPU? If so, the easiest way you can do that is by  defining the envar `TF_XLA_FLAGS=--tf_xla_cpu_global_jit`. I won't expect it to make a big difference since the bulk of the operators are placed in GPU.

What would be the rationale behind enabling XLA for CPU? Perhaps if we fully understand we'll guide you better.

**Comment by vilmara** [comment]
Hi @pribalta, I just was curious if XLA for CPU brings gain performance. Thanks!

**Comment by np-n** [comment]
I have exported `TF_XLA_FLAGS` variable using `export TF_XLA_FLAGS=--tf_xla_cpu_global_jit` works for me.
