### ISSUE TITLE
Where does these magic optimization flags come from? any Docs?

### ISSUE THREAD

**Issue by chychen** [NVIDIA/DeepLearningExamples#57]
## Environment Variables
https://github.com/NVIDIA/DeepLearningExamples/blob/c71a3fe05b05f736cb108186d8698c085b6bdeb0/TensorFlow/Segmentation/UNet_Industrial/runtime/runner.py#L131

```python
        # ============================================
        # Optimisation Flags - Do not remove
        # ============================================

        os.environ['CUDA_CACHE_DISABLE'] = '0'

        os.environ['HOROVOD_GPU_ALLREDUCE'] = 'NCCL'

        # os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

        os.environ['TF_GPU_THREAD_MODE'] = 'gpu_private'
        os.environ['TF_GPU_THREAD_COUNT'] = '1' if not hvd_utils.is_using_hvd() else str(hvd.size())

        os.environ['TF_USE_CUDNN_BATCHNORM_SPATIAL_PERSISTENT'] = '1'

        os.environ['TF_ADJUST_HUE_FUSED'] = '1'
        os.environ['TF_ADJUST_SATURATION_FUSED'] = '1'
        os.environ['TF_ENABLE_WINOGRAD_NONFUSED'] = '1'

        os.environ['TF_SYNC_ON_FINISH'] = '0'
        os.environ['TF_AUTOTUNE_THRESHOLD'] = '2'
        os.environ['TF_DISABLE_NVTX_RANGES'] = '1'

        # =================================================
```

## Session Configuration
https://github.com/NVIDIA/DeepLearningExamples/blob/c71a3fe05b05f736cb108186d8698c085b6bdeb0/TensorFlow/Segmentation/UNet_Industrial/runtime/runner.py#L290
```python
        config.gpu_options.force_gpu_compatible = True  # Force pinned memory

        if mode == 'train':
            config.intra_op_parallelism_threads = 1  # Avoid pool of Eigen threads

            if hvd_utils.is_using_hvd():
                config.inter_op_parallelism_threads = max(2, (multiprocessing.cpu_count() // hvd.size()) - 2)
            else:
                config.inter_op_parallelism_threads = 4
```

**Comment by DEKHTIARJonathan** [comment]
Here are a few pointers which might help you to find the answer to your questions:

### From documentation NVIDIA CUDA documentation

NVIDIA CUDA C Documentation: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars

* **CUDA_CACHE_DISABLE:** Disables caching (when set to 1) or enables caching (when set to 0) for just-in-time-compilation. When disabled, no binary code is added to or retrieved from the cache.

* **CUDA_CACHE_MAXSIZE:** Specifies the size in bytes of the cache used by the just-in-time compiler. Binary codes whose size exceeds the cache size are not cached. Older binary codes are evicted from the cache to make room for newer binary codes if needed.

* **CUDA_CACHE_PATH:** Specifies the folder where the just-in-time compiler caches binary codes. Defaults to ~/.nv/ComputeCache on Linux

* **CUDA_FORCE_PTX_JIT:** When set to 1, forces the device driver to ignore any binary code embedded in an application (see Application Compatibility) and to just-in-time compile embedded PTX code instead. If a kernel does not have embedded PTX code, it will fail to load. This environment variable can be used to validate that PTX code is embedded in an application and that its just-in-time compilation works as expected to guarantee application forward compatibility with future architectures.

### Horovod GPU-related options 
Documentation: https://github.com/horovod/horovod/blob/498f1bf0a6533acd640570749facca10f481c8ef/docs/gpus.md

### Tensorflow Options

* **TF_GPU_THREAD_MODE:** Whether and how the GPU device uses its own threadpool. Possible values:
  * global: GPU uses threads shared with CPU in the main compute thread-pool. This is currently the default.
  * gpu_private: GPU uses threads dedicated to this device.
  * gpu_shared: All GPUs share a dedicated thread pool.

* **TF_GPU_THREAD_COUNT:** "The number of threads to use for GPU. Only valid when tf_gpu_thread_mode is not global.

* **TF_ADJUST_HUE_FUSED:** The TF_ADJUST_HUE_FUSED variable enables the use of fused kernels for the image hue. See: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tf_adjust_hue_fused

* **TF_ADJUST_SATURATION_FUSED:** The TF_ADJUST_SATURATION_FUSE variable enables the use of fused kernels for the saturation adjustment. https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tf_adjust_saturation_fused

* **TF_ENABLE_WINOGRAD_NONFUSED:** The TF_ENABLE_WINOGRAD_NONFUSED variable enables the use of the non-fused Winograd convolution algorithm. See: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tf_enable_winograd_nonfused

* **TF_SYNC_ON_FINISH:** _Deprecated_ -  Block until device has finished all queued operations in a step if true.
* **TF_AUTOTUNE_THRESHOLD:** The TF_AUTOTUNE_THRESHOLD variable improves the stability of the auto-tuning process used to select the fastest convolution algorithms. Setting it to a higher value improves stability, but requires a larger number of trial steps at the beginning of training before the best algorithms are found. See: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tf_autotune_threshold

* **TF_DISABLE_NVTX_RANGES:** Specific to our docker containers, we have automatic debug nvtx ranges, which are not necessary for production. Only used to profile GPU performance using Nsight Systems. See: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-user-guide/index.html#tf_disable_nvtx_ranges


-----------------

* `config.gpu_options.force_gpu_compatible = True`:  Force all tensors to be gpu_compatible. On a GPU-enabled TensorFlow, enabling this option forces all CPU tensors to be allocated with Cuda pinned memory. Normally, TensorFlow will infer which tensors should be allocated as the pinned memory. But in case where the inference is incomplete, this option can significantly speed up the cross-device memory copy performance as long as it fits the memory. Note that this option is not something that should be enabled by default for unknown or very large models, since all Cuda pinned memory is unpageable, having too much pinned memory might negatively impact the overall host system performance. See: https://github.com/tensorflow/tensorflow/blob/b2b350b6a3cf805a2646c113ad4570703e79132c/tensorflow/core/protobuf/config.proto#L98

* `config.intra_op_parallelism_threads = 1`: The execution of an individual op (for some op types) can be parallelized on a pool of intra_op_parallelism_threads. 0 means the system picks an appropriate number. See: https://github.com/tensorflow/tensorflow/blob/b2b350b6a3cf805a2646c113ad4570703e79132c/tensorflow/core/protobuf/config.proto#L344

* `config.inter_op_parallelism_threads = 1`: Nodes that perform blocking operations are enqueued on a pool of inter_op_parallelism_threads available in each process.. See: https://github.com/tensorflow/tensorflow/blob/b2b350b6a3cf805a2646c113ad4570703e79132c/tensorflow/core/protobuf/config.proto#L355

--------------

I hope this will give you all the information you need.

**Comment by iperov** [comment]
I don't know why, but ```CUDA_CACHE_MAXSIZE``` is ignored by cuda.
