### ISSUE TITLE
BERT Pretraining: Why is grad_accum_steps so high?

### ISSUE THREAD

**Issue by Genius1237** [NVIDIA/DeepLearningExamples#599]
I've tried using the scripts to perform BERT pretraining. WIth `grad_accum_steps` set to 1, my effective batch size across 8 GPUs is able to match the batch size of 256 used by Devlin et al in their original pretraining. 

The issue with setting `grad_accum_steps` to 1 is that training is very slow. I have to set this to something like 16, (which still isn't Ideal) to observe more sane training times. In all the examples in this repo, `grad_accum_steps` is set to values like 512 and 1024. I do not understand why this is done. Isn't large batch training only worried about when you're training on an obscene number of GPUs? For training on 8/16 GPUs, aren't smaller batches enough? Or is there some limitation with the hardware that requires this approach?

**Comment by sharathts** [comment]
Accumulation steps are high to mimic large batch training on a small number of gpus. Hence you are not limited my the number of gpus available.

Devlin et all uses b256 with AdamW, which can't scale beyond 2k batchsizes. We use LAMB optimizer that allows you to scale batch size to 65536 and converge in far fewer steps. 8k in comparison to 1M. On settings with fewer gpus, accumulation gives larger training speedups since communication across gpus is reduced.

**Comment by Genius1237** [comment]
Thanks for the update. Had one more question. I am working with `bert-base` and couldn't find any examples in the repo for hyperparams that have been tested for `bert-base`. From what I understand, large batch training of bert-base is difficult. Are there any numbers for `bert-base` available?
