### ISSUE TITLE
Fastertransformer with tensorflow-serving

### ISSUE THREAD

**Issue by 652994331** [NVIDIA/DeepLearningExamples#614]
Hi, i was using the Fastertransformer locally, it's pretty good. we have good inference speed now. For many online application, we usually use tensorflow-serving, So, do you guys have plan to implement Fastertransformer with tensorflow-serving or is there any exist method. Thanks

**Comment by byshiue** [comment]
Currently, we don't have plan to support the tf-serving because there are many different pre-processing and post-processing for BERT model.
A possible method to run FasterTransformer on tf-serving is running FasterTransformer on TensorFlow first, freeze the graph, and than run the graph on tf-serving. This is similar to original idea to run TensorFlow graph on tf-serving, except that we replace some ops by FasterTransformer.

**Comment by dhruvsakalley** [comment]
I know this issue is closed, one downside to tensorflow serving, saved model approach is the fixing of signature on the serving function with placeholders of fixed length does extra work when inferring shorter sequences. Any ideas regarding how the max_seq_len could be optimally handled based on the true batch max_seq_len?

**Comment by byshiue** [comment]
This may require some additional works, but it is possible to solve this problem.
You can split the "max_seq_len" and "inference_seq_len". The former one is used to allocate the buffer, but latter one is used during inference to determine the grid/block size.

**Comment by dhruvsakalley** [comment]
Ideally, if the serving function uses text transforms, and accepts an input sequence embedding tokenization inside the model function, that could simplify the whole preprocessing step for the clients. Refer: https://blog.tensorflow.org/2020/06/part-2-fast-scalable-and-accurate-nlp.html
