### ISSUE TITLE
NanLossDuringTrainingError when training BERT large model

### ISSUE THREAD

**Issue by LiweiPeng** [NVIDIA/DeepLearningExamples#78]
I have been using the BERT with FP16 + XLA implementation for several weeks. It works great for BERT BASE model training. Recently I started to use it to train LARGE model with FP16+XLA. The training went well until around 344k step. It hit NanLossDuringTrainingError with error "Model diverged with loss = NaN.". The error stack with tf 1.13.1 is below. Can you provide some insights on what's wrong? Thanks.

Model diverged with loss = NaN.
Error recorded from training_loop: NaN loss during training.
training_loop marked as finished
WARNING: Reraising captured error
Traceback (most recent call last):
  File "run_pretraining.py", line 610, in 
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_pretraining.py", line 582, in main
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2457, in train
    rendezvous.raise_errors()
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2452, in train
    saving_listeners=saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model_default
    saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1407, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1335, in run
    run_metadata=run_metadata))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 753, in after_run
    raise NanLossDuringTrainingError
</pre>

**Comment by thorjohnsen** [comment]
Hi Liwei, what hyper-parameters did you use? If possible, can you give me the command line you used.

**Comment by LiweiPeng** [comment]
The command line I used is copied below.  I am using 60 V100 32GB across 15 nodes. The cluster has RDMA RoCE, OpenMPI 3.1.1, Horovod 0.16.2 (some MPI options are for RDMA RoCE). The learning rate is scaled linearly with hvd.size() inside the code.

mpirun --machinefile m.txt --map-by ppr:4:node -x HOROVOD_MPI_THREADS_DISABLE=1 --mca btl openib,self,smcuda --mca btl_openib_cpc_include rdmacm --mca btl_openib_rroce_enable 1  --mca btl_openib_receive_queues P,256,256::S,128,256,192,128:S,2048,1024,1008,64:S,12288,1024,1008,64:S,131072,1024,1008,64 --mca btl_openib_cuda_async_recv false -x NCCL_CHECKS_DISABLE=1 -x NCCL_SHM_DISABLE=0 -x NCCL_IB_DISABLE=0 -x NCCL_IB_GID_INDEX=3 -x NCCL_IB_CUDA_SUPPORT=1 python run_pretraining.py --input_file=data/*/*.tfrecord --output_dir=model --do_train=True --do_eval=True --bert_config_file=bert_config.json --train_batch_size=12 --max_seq_length=512 --max_predictions_per_seq=77 --num_train_steps=700000 --num_warmup_steps=10000 --learning_rate=1e-6 --save_checkpoints_steps=1000 --horovod --report_loss --use_fp16 --use_xla

**Comment by LiweiPeng** [comment]
More information: after NanLossDuringTrainingError occurred, I won't be able to use mixed precision to train bert. however, after I switch to fp32 only, I can continue training, but it is much slower.

**Comment by nvcforster** [comment]
We would like to reproduce the errors you are seeing, and it would be helpful to get more information about your data/preprocessing/training.

To cover the basics, your system and versions look reasonable. The learning rate is sufficiently small, with enough warmup steps for the global batch size you are using (720). The maximum predictions per sequence is in the expected range for the maximum sequence length. The fact that it converges in FP32 suggests your data preparation should be correct for the BERT-large model configuration, assuming it converges to the expected accuracy.

As a first step in trying to diagnose this, would it be possible to get your loss curves during a pretraining run? If you do not wish to post these here, we can get in contact directly. After seeing what the loss curves look like, we can investigate other potential sources of issues to get to the root cause.

**Comment by LiweiPeng** [comment]
Thanks @nvcforster . I'll get the loss curve and share it with you.

**Comment by LiweiPeng** [comment]
<img width="836" alt="loss" src="https://user-images.githubusercontent.com/8562078/59554259-48ed1580-8f55-11e9-9295-6153ed8b0f9f.png">

**Comment by LiweiPeng** [comment]
@nvcforster The above is the loss curve. unfortunately, I lost the log file in the middle of the training  among multiple restarts.

**Comment by nvcforster** [comment]
@LiweiPeng Thanks for sending these. There are two paths that we can look at.

1) I realized I may have missed something in the logs on Friday. Is this being run from within the NVIDIA container with some packages updated, or is this the code from GitHub being run on the host system or another container with a standard TF install? The reason I ask is that our containers may contain items that get upstreamed into TF slightly later due to release cycles, and we should make sure we are operating on the equivalent versions to ensure all components of AMP for TF are present/up-to-date. You can see the container config with `printenv` and `pip freeze`.

2) Are you using a public dataset? If so, which one?

**Comment by LiweiPeng** [comment]
@nvcforster To answer your questions: 1) I am using your code from the github on a host system; 2) My original dataset was private dataset. However, I reproduced the issue when using the Chinese wikipedia public dataset (https://dumps.wikimedia.org/zhwiki/latest/zhwiki-latest-pages-articles.xml.bz2)

**Comment by nvcforster** [comment]
The ideal and officially supported method is to use the NVIDIA Docker images since we test these to ensure everything works out of the box. Would you be able to run pretraining inside of this container? 

The upstream TensorFlow minimum version required is 1.14, which is currently only available as a release candidate.

Please let us know which options are available to you. We would like to verify this resolves the problem.

**Comment by LiweiPeng** [comment]
Thanks Chris. The same issue was also reproduced using TF 1.14 rc0.

I didn't use nvidia docker image. what difference could it make between using the docker container vs using host system with the same TF and github code?

**Comment by nvcforster** [comment]
Thanks for checking this. We will dig into this on our end.

Docker is a nice way of encapsulating an environment with a known working installation of our software stack (TF, libraries, CUDA, etc.), and it helps remove variables when debugging on different machines. It isn't strictly required, but it can save a lot of work.

**Comment by LiweiPeng** [comment]
Thanks Chris. FYI, the issue was reproduced in 2 different clusters. One is TF 1.13.1, the other one is TF 1.14 rc0.

**Comment by mengdong** [comment]
among runs in 2 different clusters, did you do restart and recover from a checkpoint in both cases?

**Comment by LiweiPeng** [comment]
yes, both clusters were restarted multiple times but the issue was still
there.

**Comment by LiweiPeng** [comment]
@thorjohnsen @nvcforster I reproduced this issue using my checkpoint with this github's code and public chinese wikipedia dataset. The details were sent to you separately by email

**Comment by j0x7c4** [comment]
Be careful with log operation,  since you could easily get extreme small probability in some class after calculating softmax, and maybe get 0 if using low precision like fp16. 
however, code  `log_probs = tf.nn.log_softmax(logits, axis=-1)` can be modified to `probabilities = tf.nn.softmax(logits, axis=-1) `
`log_probs = tf.log(tf.clip_by_value(probabilities,1e-8,1.0))` in order to avoid probability 0

**Comment by Jimojimojimo** [comment]
How did you solve this problem?
