### ISSUE TITLE
[Fast Transformer] Is there anyway to do int8 quantization without calibration ?

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/DeepLearningExamples#799]
We need a calibration dataset to collect the scalar of quantization which is  really inconvenient when we do int8 quantization.  It would be nice if we make a int8 conversion like a data type conversion. So could we make int8 inference without calibration ?  
As I think, we can get the quantization scalar according to the current input just with a simple max function instead of percentile or MSE to get the scalar.   Although max function sometimes introduce the outlier , it just consider the current input values and we can do per-channel quantization on it which maybe increase the precision. Besides, we can use kernel fused to get the max inside gemm casing little cost.

**Comment by byshiue** [comment]
Thanks for your feedback, this is a possible direction. However, there are some issues. 
1. Calibration is necessary if we want to use QAT. So, we are only able to use PTQ if we get the max value during inference. And this may lead to significant accuracy loss. 
2. Currently, cublaslt requires the calibration information as inputs when the output is int8. Otherwise, we are only able to use int32 output and the speed would be slow. (at most 1.3x speedup). We can overcome this problem by implementing a high efficient kernel containing "gemm + dequantization + reduction + quantization". However, this is a very hard work.

**Comment by ligonzheng** [comment]
Thank you for your reply ! Maybe there are some space for research.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
