### ISSUE TITLE
'ascii' codec can't decode byte 0xc2 in position 318: ordinal not in range(128)

### ISSUE THREAD

**Issue by visualxu** [NVIDIA/DeepLearningExamples#842]
Related to **Model/Framework(s)** 
*(e.g. GNMT/PyTorch or FasterTransformer/All)*

**Describe the bug**
When i execute "python main.py" in PyTorch/Translation/GNMT, The complier print "error : codecs.ascii_decode(input, self.errors)[0] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 318: ordinal not in range(128)".
And i change code "with open(fname,'r')"  which is contained by tokenizer.py and dataset.py  to "codecs.open(fname, 'r', 'UTF-8')", the problem will not appear.I don't know whether this problem is caused by my environment.(For some reason,i don't use container which you provided)

**To Reproduce**
1. git clone https://github.com/NVIDIA/DeepLearningExamples
2.cd DeepLearningExamples/PyTorch/Translation/GNMT
3.bash scripts/wmt16_en_de.sh
4.python3 train.py

**Expected behavior**
The code runs successfully. 

**Environment**
Please provide at least:
* Continer(python3.6 , pytorch1.6):
* GPUs in the system: (e.g. 1080Ti 12GB):
* CUDA driver version (e.g. 440.64.00):

**Comment by szmigacz** [comment]
It happens because the dataset contains non-ascii characters. The default encoding for `open` is platform-dependent and it's sourced from the environment. Everything works fine in the container because Dockerfile (https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Translation/GNMT/Dockerfile) sets:
```
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
```
and this is automatically picked up by `open` which in the container by default selects UTF-8 decoder.

I think this issue should be closed, I don't want to manually hardcode decoder to UTF-8 in every single call to open, it's better to source it from environment and have one location where this needs to be changed in case somebody wants to use this example to train on a different dataset which may be using different encoding. Do you agree?

**Comment by visualxu** [comment]
That is a deal.Thanks for your answer. I should read the dockfile when i decided use my environment.

**Comment by szmigacz** [comment]
Thanks for the verification. I'm closing the issue. Feel free to reopen if you have further questions.
