### ISSUE TITLE
[Question/SpeechRecognition/Japser]

### ISSUE THREAD

**Issue by songtaoshi** [NVIDIA/DeepLearningExamples#855]
Hi, I cannot understand the description "Jasper architecture of convolutional layers was designed to facilitate fast GPU inference, by allowing **whole sub-blocks to be fused into a single GPU kernel**. "  Why can Jasper sub-blocks be fused into a single GPU kernel and Why it can accelerate the model inference?
@aaronp24 @lxp121 @lukeyeager @moconnor725 @372046933

**Comment by qijiaxing** [comment]
maybe it means TensorRT can fuse the sub-block (conv + bn + relu + dropout).

**Comment by alancucki** [comment]
Fusing subsequent kernels speeds up the computation. Every kernel launch brings an overhead, and some kernels are bottlenecked by the bandwith of moving the activations in and out of DRAM. When kernels are fused, the intermediate activations remain local. Even more so during the inference: the activations do not have to be stored for the backward pass, because there isn't one.

Every framework provides support for kernel fusion separately. For instance, in TensorRT it happens automatically for supported layers (see https://docs.nvidia.com/deeplearning/tensorrt/best-practices/index.html#fusion-types). Jasper's architecture makes use of those fusable kernels. This can be observed by increasing the verbosity of [TensorRT export function](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechRecognition/Jasper/triton/pytorch/utils.py#L66):
```
# TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)
```

The verbose output displays the fused kernels, and they snowball rapidly:
```
[TensorRT] VERBOSE: Fusing (Unnamed Layer* 2476) [Constant] with (Unnamed Layer* 2477) [ElementWise]
[TensorRT] VERBOSE: Fusing PWN((Unnamed Layer* 2476) [Constant], (Unnamed Layer* 2477) [ElementWise]) with (Unnamed Layer* 2478) [Unary]
[TensorRT] VERBOSE: Fusing PWN(PWN((Unnamed Layer* 2476) [Constant], (Unnamed Layer* 2477) [ElementWise]), (Unnamed Layer* 2478) [Unary]) with (Unnamed Layer* 2480) [ElementWise]
[TensorRT] VERBOSE: Fusing (Unnamed Layer* 2479) [ElementWise] with PWN(PWN(PWN((Unnamed Layer* 2476) [Constant], (Unnamed Layer* 2477) [ElementWise]), (Unnamed Layer* 2478) [Unary]), (Unnamed Layer* 2480) [ElementWise])
[TensorRT] VERBOSE: Fusing PWN((Unnamed Layer* 2479) [ElementWise], PWN(PWN(PWN((Unnamed Layer* 2476) [Constant], (Unnamed Layer* 2477) [ElementWise]), (Unnamed Layer* 2478) [Unary]), (Unnamed Layer* 2480) [ElementWise])) with (Unnamed Layer* 2481) [ElementWise]
[TensorRT] VERBOSE: Fusing PWN(PWN((Unnamed Layer* 2479) [ElementWise], PWN(PWN(PWN((Unnamed Layer* 2476) [Constant], (Unnamed Layer* 2477) [ElementWise]), (Unnamed Layer* 2478) [Unary]), (Unnamed Layer* 2480) [ElementWise])), (Unnamed Layer* 2481) [ElementWise]) with BatchNormalization_274 + Relu_275

...

```
