### ISSUE TITLE
[TensorFlow2/WideAndDeep] Limited scaling for multi-GPU

### ISSUE THREAD

**Issue by Peach-He** [NVIDIA/DeepLearningExamples#894]
Is it a known issue that W&D has bad scaling for multi-GPU? The performance data showed that scale from 1 GPU to 8 GPU, we can only get about 2x performance gain.
If this is a known issue, any idea about the root cause?

Thanks

**Comment by PiotrBigajNV** [comment]
Hi Peach-He,
There are following reasons for the numbers you quote:
1. Wide and Deep on Outbrain dataset produces, by modern recommender standards, a small model. Larger models should still see significant benefits of using multi-GPU 
2. Current Data Loader is CPU bound. This can be especially seen in multi-GPU setup. We constantly work on upgrading the Data Loader for this model to make it even faster than it is. With new Data Loader we hope to achieve higher performance and better scaling. 
3. The scaling you mention is a Strong scaling meaning that we have BS as a global parameter. Setting BS like that means that when training on N GPUs effective batch size per GPU is `BS/N`. This means that when we have `BS=131072`  and `8 GPU` each GPU receives only `16k` batch. If you would run Weak Scaling (compensating Global BS) and set global `BS=8*131072` then you can calculate scaling having the same Batch sizes. In order to achieve the same BS per GPU for ` BS=16k` can be achieved by setting BS=16k (by setting `--global_batch_size` flag to `16k`) for single GPU and 131072 for 8 GPUs. In some of our experiments when having the same BS per GPU e.g. for` DGX A100` for global `BS=131072`, TF32 we have achieved approx.` 4.5x` speedup (`8 GPUs` vs `1 GPU`). With the same setup for AMP the speedup was approx. 4x. For `DGX-1` for global `BS=131072` without `XLA` the weak scaling for `FP32` was approx. `5.9x`.

Please note that these values are approximate. They come from single measurement - In readme you have the number from 20 experiments for every single configuration. 

We're constantly refining and improving our performance on AI and HPC workloads even on the same hardware with frequent updates to our software stack. For our latest performance data please refer to these pages for AI and HPC benchmarks.

**Comment by Peach-He** [comment]
Thanks for your reply @PiotrBigajNV , but I am a little confused, please correct me.
If I understand correctly, the performance data you mentioned 4x+ speedup is for inference performance, right? Than it is true that we can get 4x+ speedup for both strong and weak scaling.
When we come to training performance, take training time as example, the scaling performance is much worse, about 2x speedup. And we achieved 2x speedup (4 nodes vs 1 node, training on CPU)  with strong and weak scaling. How to explain the training performance here?
![image](https://user-images.githubusercontent.com/51695408/113381320-3e617180-93b1-11eb-8252-a9cabf96d8e0.png)

**Comment by PiotrBigajNV** [comment]
Hi @Peach-He ,
Everything that I have wrote [here](https://github.com/NVIDIA/DeepLearningExamples/issues/894#issuecomment-811935451) is for training part, not for inference. For point 3 the cited speedups are for Weak Scaling.

We did not measure training performance on CPU as you mention, only on GPU. The numbers are not for 4 "nodes", but 1 and 8 GPUs on a single supercomputer.

The table that you pasted here still assumes Strong Scaling. If you would measure it with Weak Scaling then E2E training time will also improve. Please note that the performance speedup is not 1:1 with E2E train speedup as throughput does not take into account model initialization and other setup.

Does this clarifies situation?
