### ISSUE TITLE
why use the function 'get_train_step' in image_classification/training.py?

### ISSUE THREAD

**Issue by YYangZiXin** [NVIDIA/DeepLearningExamples#952]
why use the function 'get_train_step' in image_classification/training.py? 
I try to move the code in  function '_step' to  function 'train' , the memory cost increase a lot. 
Why this happens？What's your motivation to put the training code inside of funtion  '_step'  inside of funtion  'get_train_step' ?

**Comment by asulecki** [comment]
Hi,

Why do we have functions at all? Dividing code into functions usually improves readability and reusability of code.

I can’t help you with your issue since you didn’t post the code, and I don’t understand why you want to put the step code inside the train function in the first place.

Since it is not really an issue with this code base, I’m closing it. Please reopen if you have more questions.
