### ISSUE TITLE
The problem about Inference NCF model

### ISSUE THREAD

**Issue by taquanghung1705199** [NVIDIA/DeepLearningExamples#985]
I am a newbie. I have a question about the recommendation system
How to inference result for user after I have model ? (Ex: Top 10 customer favorite items)
I watched how inference from:
https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/NCF#inference-process
But it only show the model quality parameters 

Please help me !

**Comment by tgrel** [comment]
Hi @taquanghung1705199 ,

I think you could use a function like this for your usecase.

`def inference(model, user, item, k=10):
    model.eval()

    with torch.no_grad():
        out = model(user, item)
        out = torch.topk(out, k)[0]
    return output
`
I haven't tested it, so it might need some tweaking, but hopefully it'll be helpful.

Best regards,
Tomasz

**Comment by taquanghung1705199** [comment]
Thanks @tgrel 
I have 1 more question
if input is a new user (this user is not trained in model). How to recommend for this user ?

**Comment by tgrel** [comment]
In the recommender system literature this problem is often referred to as "cold start". This repository doesn't provide a solution to it. Technically, if you don't have an embedding trained for the particular user the model cannot make a recommendation for them. I'm not an expert on "cold start" so cannot really give good advice.

I'm sure you'll be able to find some reasonable solution in the literature about the subject. A good place to start reading up on this is [this wikipedia entry about cold start](https://en.wikipedia.org/wiki/Cold_start_(recommender_systems)).

Good luck!
Tomasz
